# Generated by Django 6.0.2 on 2026-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, verbose_name='Descriptions')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=200)),
                ('board_university', models.CharField(blank=True, max_length=100, null=True)),
                ('passing_year', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-passing_year'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('AL', 'Annual Leave')], max_length=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected/Cancelled')], default='PENDING', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(db_index=True, help_text='e.g. 1001', max_length=20, null=True, unique=True, verbose_name='Staff ID')),
                ('device_user_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Biometric Device ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='নামের প্রথম অংশ')),
                ('last_name', models.CharField(max_length=30, verbose_name='নামের শেষ অংশ')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='পিতার নাম')),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name='মাতার নাম')),
                ('nid_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NID নম্বর')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Primary Phone')),
                ('emergency_contact', models.CharField(blank=True, max_length=15, verbose_name='Emergency Contact')),
                ('present_address', models.TextField(blank=True, verbose_name='বর্তমান ঠিকানা')),
                ('permanent_address', models.TextField(blank=True, verbose_name='স্থায়ী ঠিকানা')),
                ('designation', models.CharField(max_length=100, verbose_name='পদবি')),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('probation', 'Probation'), ('contractual', 'Contractual'), ('intern', 'Intern')], default='probation', max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('shift_type', models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency'), ('Overtime', 'Overtime'), ('Double', 'Double')], default='Regular', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('late_grace_period', models.PositiveIntegerField(default=15, help_text='মিনিটে (যেমন: ১৫ মিনিট পর্যন্ত ছাড়)')),
                ('is_active', models.BooleanField(default=True)),
                ('color_code', models.CharField(default='#0d6efd', max_length=10)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
