# Generated by Django 6.0.2 on 2026-05-31 18:23

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='অ্যাকশন কী (e.g., create, view)')),
                ('name_bn', models.CharField(max_length=50, verbose_name='অ্যাকশন নাম (বাংলা)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রমিক নম্বর')),
            ],
            options={
                'verbose_name': 'অ্যাকশন টাইপ',
                'verbose_name_plural': 'অ্যাকশন টাইপসমূহ',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ModuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='গ্রুপের নাম')),
                ('icon', models.CharField(default='bi-folder', max_length=50, verbose_name='আইকন ক্লাস (Bootstrap/FontAwesome)')),
                ('icon_unicode', models.CharField(blank=True, max_length=10, null=True, verbose_name='আইকন ইউনিকোড')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রমিক নম্বর')),
            ],
            options={
                'verbose_name': 'মডিউল গ্রুপ',
                'verbose_name_plural': 'মডিউল গ্রুপসমূহ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ইমেইল অ্যাড্রেস')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='ইউজারনেম')),
                ('is_active', models.BooleanField(default=True, verbose_name='অ্যাকাউন্ট সক্রিয়')),
                ('is_staff', models.BooleanField(default=False, verbose_name='স্টাফ স্ট্যাটাস (অ্যাডমিন প্যানেল অ্যাক্সেস)')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='সুপার ইউজার স্ট্যাটাস')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_protected', models.BooleanField(default=False, verbose_name='সুরক্ষিত ইউজার')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী',
                'verbose_name_plural': 'ব্যবহারকারীগণ',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='মডিউলের নাম (ইংরেজী)')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='লেবেল (বাংলা)')),
                ('url_name', models.CharField(max_length=100, unique=True, verbose_name='ইউআরএল নেমস্পেস (Namespace URL)')),
                ('class_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='CSS/JS ক্লাস টার্গেটিং')),
                ('icon', models.CharField(default='bi-circle', max_length=50, verbose_name='আইকন ক্লাস')),
                ('icon_unicode', models.CharField(blank=True, max_length=10, null=True, verbose_name='ইউনিকোড আইকন')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রমিক নম্বর')),
                ('is_visible', models.BooleanField(default=True, verbose_name='মেনুতে দৃশ্যমান কিনা')),
                ('is_header', models.BooleanField(default=False, verbose_name='হেডার দৃশ্যমানতা')),
                ('is_default', models.BooleanField(default=False, verbose_name='ডিফল্ট মডিউল')),
                ('actions', models.ManyToManyField(related_name='modules', to='mainsystem.actiontype', verbose_name='অনুমোদিত অ্যাকশনসমূহ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mainsystem.module', verbose_name='প্যারেন্ট মडीউল')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='mainsystem.modulegroup', verbose_name='মডিউল গ্রুপ')),
            ],
            options={
                'verbose_name': 'মডিউল',
                'verbose_name_plural': 'মডিউলসমূহ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(db_index=True, default=False, verbose_name='অনুমতি আছে?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='mainsystem.actiontype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='mainsystem.module')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ম্যাট্রিক্স পারমিশন',
                'verbose_name_plural': 'ম্যাট্রিক্স পারমিশনসমূহ',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='রোলের নাম')),
                ('is_protected', models.BooleanField(default=False, verbose_name='সুরক্ষিত রোল (মুছে ফেলা যাবে না)')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('modules', models.ManyToManyField(through='mainsystem.Permission', to='mainsystem.module', verbose_name='অ্যাক্সেসযোগ্য মডিউলসমূহ')),
            ],
            options={
                'verbose_name': 'ইউজার রোল',
                'verbose_name_plural': 'ইউজার রোলসমূহ',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='mainsystem.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainsystem.role', verbose_name='ইউজার রোল'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('role', 'module', 'action')},
        ),
    ]
