# Generated by Django 6.0.2 on 2026-05-31 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manualentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualentry',
            name='default_entry',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='first_entry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='second_entry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manualentry',
            name='total_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manualentry.terminal'),
        ),
    ]
